# Generated by Django 5.0.4 on 2026-05-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Nom affiché')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service_type', models.CharField(choices=[('api', 'API REST'), ('worker', 'Worker / Queue'), ('database', 'Base de données'), ('cache', 'Cache'), ('proxy', 'Proxy / LB'), ('scheduler', 'Planificateur'), ('other', 'Autre')], default='api', max_length=15, verbose_name='Type')),
                ('status', models.CharField(choices=[('operational', 'Opérationnel'), ('degraded', 'Dégradé'), ('partial', 'Panne partielle'), ('major', 'Panne majeure'), ('maintenance', 'Maintenance'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=15, verbose_name='Statut')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('endpoint', models.URLField(blank=True, verbose_name='URL / Endpoint')),
                ('avg_latency_ms', models.FloatField(blank=True, null=True, verbose_name='Latence moy. (ms)')),
                ('p95_latency_ms', models.FloatField(blank=True, null=True, verbose_name='Latence p95 (ms)')),
                ('error_rate', models.FloatField(blank=True, null=True, verbose_name="Taux d'erreur (%)")),
                ('requests_per_sec', models.FloatField(blank=True, null=True, verbose_name='Req/s')),
                ('uptime_30d', models.FloatField(blank=True, null=True, verbose_name='Uptime 30j (%)')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Dernier check')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='logs.logsource', verbose_name='Source de logs')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_type', 'name'],
            },
        ),
    ]
