# Generated by Django 5.0.4 on 2026-05-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Développement'), ('dr', 'Disaster Recovery')], default='production', max_length=15, verbose_name='Environnement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('status', models.CharField(choices=[('online', 'En ligne'), ('offline', 'Hors ligne'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=10, verbose_name='Statut')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('cpu_percent', models.FloatField(blank=True, null=True, verbose_name='CPU (%)')),
                ('memory_percent', models.FloatField(blank=True, null=True, verbose_name='RAM (%)')),
                ('disk_percent', models.FloatField(blank=True, null=True, verbose_name='Disque (%)')),
                ('load_average', models.FloatField(blank=True, null=True, verbose_name='Load average')),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True, verbose_name='Uptime (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server', to='logs.logsource', verbose_name='Source de logs')),
            ],
            options={
                'verbose_name': 'Serveur',
                'verbose_name_plural': 'Serveurs',
                'ordering': ['environment', 'name'],
            },
        ),
    ]
