# Generated by Django 5.0.4 on 2026-05-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom')),
                ('source_type', models.CharField(choices=[('server', 'Serveur'), ('service', 'Service'), ('application', 'Application'), ('database', 'Base de données'), ('network', 'Réseau'), ('security', 'Sécurité')], default='application', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname / IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source de logs',
                'verbose_name_plural': 'Sources de logs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Horodatage')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], db_index=True, default='INFO', max_length=10, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message')),
                ('logger_name', models.CharField(blank=True, max_length=200, verbose_name='Logger')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données additionnelles')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Fichier')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ligne')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('ingested_at', models.DateTimeField(auto_now_add=True, verbose_name='Ingéré le')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='logs.logsource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Entrée de log',
                'verbose_name_plural': 'Entrées de logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'timestamp'], name='idx_level_timestamp'), models.Index(fields=['source', 'timestamp'], name='idx_source_timestamp'), models.Index(fields=['timestamp'], name='idx_timestamp')],
            },
        ),
    ]
